# Generated by Django 2.2.8 on 2019-12-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Basligi')),
                ('author', models.CharField(max_length=50, verbose_name='Muellifi')),
                ('page_count', models.PositiveIntegerField(verbose_name='Sehife')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qiymeti')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books_cover/', verbose_name='Uz Qabigi')),
                ('description', models.TextField(verbose_name='Aciqlama')),
                ('subject', models.IntegerField(choices=[(1, 'Dram'), (2, 'Comedy'), (3, 'Detective')], default=1)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='books_pdfs/', verbose_name='Uz Qabigi')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'my_books',
            },
        ),
    ]
