# Generated by Django 2.2.8 on 2019-12-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20191217_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True, verbose_name='Product adi')),
                ('description', models.TextField(max_length=500, verbose_name='Aciqlama')),
                ('category', models.IntegerField(choices=[(0, 'Convenience Goods'), (1, 'Shopping Goods'), (2, 'Specialty Goods')], default=1)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='model_project/media/products/images/', verbose_name='Sekil')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Miqdari')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Qiymeti')),
                ('production_date', models.DateTimeField(auto_now_add=True, verbose_name='Istehsal_tarixi')),
                ('is_new', models.BooleanField(blank=True, default=False, null=True, verbose_name='Veziyyeti')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='model_project/media/products/files/', verbose_name='Sertifikat')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True, verbose_name='Rating')),
                ('detailed_view_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('price',), 'verbose_name': 'Kitab', 'verbose_name_plural': 'Kitablar'},
        ),
    ]
