# Generated by Django 2.2.8 on 2019-12-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20191217_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='products/files/', verbose_name='Sertifikat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Sekil'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='company_products',
        ),
    ]
